theme: jekyll-theme-leap-day
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
ctx:
    - text: Про себе
      url: /about/
    - text: Проекти
      url: /projects/
    - text: Корисні лінки
      url: /uflinks/
    - text: Розділ 1. Основні поняття і принципи побудови сучасних систем автоматизації 
      url: /formula/1.html
    - text: 1.1. Основні поняття і визначення
      url: /formula/1_1.html
    - text: 1.2. Принципи побудови сучасних систем автоматизації
      url: /formula/1_2.html
    - text: 1.3 Види забезпечень сучасних систем автоматизації
      url: /formula/1_3.html
    - text: 1.4 Інтегровані автоматизовані системи управління
      url: /formula/1_4.html
